"""
content_pool.py

Definitieve content pool: 15 foto-scenes + 30 tekst-only posts.
Bestandsnamen in PHOTO_SCENES matchen exact met de bestanden in images/.
"""

# 15 foto-scenes: (bestandsnaam in images/, caption)
PHOTO_SCENES = [
    ("01_headphones_phone.png", "npc bro, unbothered, checking the only thing that matters"),
    ("02_desk_trading.png", "npc bro's trading setup. no chair, no plan, all conviction"),
    ("03_green_arrow_rocket.png", "npc bro found the trajectory. npc bro is not moving."),
    ("04_crash_dive.png", "npc bro on the way down, still holding the phone"),
    ("05_coffee.png", "npc bro doesn't need coffee, npc bro needs liquidity"),
    ("06_sad_hodl.png", "npc bro closed his eyes. the chart did not close with him."),
    ("07_meme_green_candle_run.jpeg", "npc bro doesn't need a reason"),
    ("08_multi_monitor_wall.png", "npc bro's setup has more screens than friends"),
    ("09_running_phone.png", "npc bro heard about it 4 seconds ago and is already in"),
    ("10_standing_green_chart.png", "npc bro's face when it's up only. same face either way."),
    ("11_arms_crossed.png", "npc bro has made a decision. npc bro will not explain it."),
    ("12_meditation.png", "npc bro found inner peace. it's just the phone glowing."),
    ("13_confused_question.png", "npc bro doesn't know why he bought it either"),
    ("14_trophy.png", "npc bro won. npc bro is not sure at what."),
    ("15_broken_umbrella_rain.png", "npc bro's risk management, visualized"),
    # 21 nieuwe foto-scenes
    ("16_phone_chart.jpg", "npc bro found the chart. npc bro is not moving until it moves."),
    ("17_trading_screen.jpg", "npc bro's trading setup. more screens than brain cells."),
    ("18_desk_setup.jpg", "npc bro doesn't need a proper desk. npc bro needs liquidity."),
    ("19_phone_focus.jpg", "npc bro is locked in. the chart is the only thing that matters."),
    ("20_chart_stare.jpg", "npc bro has been staring at this chart for 4 hours. it hasn't moved. neither has npc bro."),
    ("21_gaming_setup.jpg", "npc bro's gaming setup. also his trading setup. also his life."),
    ("22_phone_bed.jpg", "npc bro doesn't sleep. npc bro just refreshes dexscreener horizontally."),
    ("23_desk_chair.jpg", "npc bro's ergonomic setup: whatever was on sale at ikea."),
    ("24_multiple_screens.jpg", "npc bro needs 6 screens to make decisions he doesn't understand."),
    ("25_trading_pose.jpg", "npc bro's trading posture. shoulders forward, eyes glazed, phone in hand."),
    ("26_phone_casual.jpg", "npc bro acting casual. npc bro is down 40% today."),
    ("27_desk_work.jpg", "npc bro working hard. by watching other people make money."),
    ("28_monitor_focus.jpg", "npc bro's monitor. npc bro's entire personality."),
    ("29_phone_check.jpg", "npc bro checking the chart. again. for the 47th time today."),
    ("30_trading_desk.jpg", "npc bro's command center. where dreams go to die."),
    ("31_phone_relaxed.jpg", "npc bro relaxed. npc bro just bought the top. it's fine."),
    ("32_desk_computer.jpg", "npc bro's computer. mostly used for refreshing twitter."),
    ("33_monitor_setup.jpg", "npc bro's monitor setup. designed for maximum fomo induction."),
    ("34_phone_stand.jpg", "npc bro standing. npc bro doesn't sit. npc bro doesn't think. npc bro just buys."),
    ("35_trading_focus.jpg", "npc bro in the zone. the zone where he loses money."),
]

# 30 tekst-only posts (definitieve pool)
TEXT_POSTS = [
    # Relatable degen-gedrag
    "npc bro doesn't have a thesis. npc bro has vibes and a phone.",
    "npc bro's portfolio strategy: whatever's trending at 2am",
    "npc bro doesn't sell high. npc bro sells whenever he gets nervous.",
    "npc bro's biggest indicator is how many people are talking about it. that's it. that's the whole strategy.",
    "npc bro read one tweet and changed his entire life plan",
    "npc bro doesn't have a stop loss. npc bro has regret.",
    "npc bro checks the chart 47 times a day and still doesn't know what he's looking at",
    "npc bro's risk management: hope",
    "npc bro bought high, sold low, and still calls himself a trader",
    "npc bro doesn't do technical analysis. npc bro does vibes analysis.",
    # GM/GN
    "gm to everyone. especially npc bro, who is already checking the chart before his eyes are fully open",
    "gn to everyone except npc bro, who is still refreshing dexscreener at 3am",
    "gm. npc bro slept 4 hours and dreamed about green candles",
    "gn. tomorrow npc bro wakes up and does the exact same thing again",
    # Zelfspot/community
    "be honest, how many of you are secretly npc bro",
    "npc bro isn't a person. npc bro is a mirror.",
    "we're all npc bro sometimes. some of us just admit it.",
    "there's an npc bro in every group chat. if you don't know who it is, it might be you",
    "npc bro doesn't judge. npc bro just follows. respect the process.",
    "the npc army doesn't sleep, doesn't think, and definitely doesn't dyor",
    # Hype/community-opbouw
    "npc bro is coming. no research needed to understand why.",
    "$NPCBRO isn't the smartest coin on solana. it's the most honest one.",
    "if you've ever bought something because a stranger on CT told you to, welcome home",
    "npc bro doesn't need utility. npc bro needs vibes.",
    "the most relatable character in crypto is about to get a coin",
    # Losse observaties/humor
    "npc bro's wallet has 40 different tokens and he can't explain why he bought any of them",
    "npc bro doesn't read whitepapers. npc bro reads vibes.",
    "npc bro's favorite indicator is 'this guy seems confident'",
    "npc bro has never once said 'let me do some research first'",
    "somewhere right now, npc bro is buying something because of a reply guy with a rocket emoji in his bio",
    # Hype voor pump.fun launch
    "npc bro doesn't know what pump.fun is yet. but npc bro will be there when it matters.",
    "the npc lobby is loading... prepare for entry.",
    "npc bro has been preparing for this moment his whole life. by doing absolutely nothing.",
    "when $NPCBRO launches, npc bro will be first in line. because npc bro is always first in line.",
    "npc bro doesn't need a whitepaper. npc bro needs a green button.",
    "the npc army is gathering. no coordination needed. we just follow.",
    "pump.fun? npc bro thought that was the sound his portfolio makes.",
    "npc bro's launch strategy: wait for someone else to say it's good, then ape in.",
    "the npc lobby doesn't do research. the npc lobby does vibes.",
    "npc bro is coming to solana. bring your tendies.",
    "when $NPCBRO launches, npc bro won't read the tokenomics. npc bro will just buy.",
    "the npc lobby is open. no entry requirements. just lack of critical thinking.",
    "npc bro has been training for this launch. by scrolling CT for 12 hours a day.",
    "pump.fun is just npc bro's natural habitat.",
    "npc bro doesn't know when the launch is. npc bro will find out when everyone else does.",
    "the npc army doesn't need a signal. the npc army is the signal.",
    "npc bro's due diligence: checking if the emoji looks bullish.",
    "when $NPCBRO hits pump.fun, npc bro will be there. npc bro is always there.",
    "the npc lobby doesn't sleep. the npc lobby waits for the green candle.",
    "npc bro doesn't need a roadmap. npc bro needs a chart that goes up.",
    "pump.fun + npc bro = the most honest launch in solana history.",
    "npc bro's investment thesis: if it's trending, it's good.",
    "the npc lobby is where degens become legends. or lose everything. probably both.",
    "npc bro doesn't know what solana is. npc bro just knows it goes up sometimes.",
    "when $NPCBRO launches, npc bro will buy the top. because that's what npc bro does.",
    "the npc army doesn't need instructions. the npc army needs a green candle.",
    "npc bro's pre-launch strategy: refresh CT until something looks promising.",
    "pump.fun is where npc bro belongs. it's where vibes matter more than utility.",
    "npc bro doesn't need a marketing budget. npc bro needs other npc bros.",
    "the npc lobby is growing. one degen at a time.",
    "npc bro's favorite word: 'moon'. npc bro's second favorite: 'safu'.",
    "when $NPCBRO launches, npc bro won't ask questions. npc bro will just ape.",
]

# Reply pool voor engagement op andere tweets
REPLY_POOL = [
    "based. npc bro approves.",
    "npc bro is already in.",
    "this is the npc bro signal.",
    "npc bro doesn't need to think. npc bro just buys.",
    "welcome to the npc lobby.",
    "npc bro vibes detected.",
    "this is exactly why npc bro is here.",
    "npc bro read this and immediately bought.",
    "npc bro doesn't need a reason. this is it.",
    "the npc army is watching.",
    "npc bro's portfolio: this.",
    "npc bro doesn't do research. npc bro follows vibes.",
    "this is the npc bro way.",
    "npc bro sees green. npc bro buys.",
    "welcome home, npc bro.",
    "npc bro doesn't question. npc bro follows.",
    "this is npc bro's kind of content.",
    "npc bro is locked in.",
    "the npc lobby approves.",
    "npc bro doesn't need to understand. npc bro just apes.",
    "npc bro heard about this 4 seconds ago and is already in.",
    "this is the npc bro thesis. no thesis, just vibes.",
    "npc bro doesn't need a chart. npc bro needs this.",
    "the npc army doesn't sleep. the npc army buys.",
    "npc bro's risk management: yolo.",
    "this is why npc bro is here. for this exact moment.",
    "npc bro doesn't read whitepapers. npc bro reads tweets like this.",
    "based and npc-bro-pilled.",
    "npc bro's favorite indicator: this tweet.",
    "the npc lobby welcomes you.",
    "npc bro doesn't need confirmation. npc bro has vibes.",
    "this is the npc bro way of life.",
    "npc bro sees potential. npc bro buys.",
    "welcome to the npc army.",
    "npc bro doesn't need analysis. npc bro needs action.",
    "this is exactly what npc bro was waiting for.",
    "npc bro's strategy: follow tweets like this.",
    "the npc bro signal is strong with this one.",
    "npc bro doesn't need to know why. npc bro just buys.",
    "this is npc bro's kind of alpha.",
    "npc bro is ready. npc bro is buying.",
    "the npc lobby has spoken.",
    "npc bro doesn't need logic. npc bro needs this.",
    "this is the npc bro way to make it.",
    "npc bro sees the vision. npc bro apes.",
    "welcome to the npc bro lifestyle.",
    "npc bro doesn't need proof. npc bro has faith.",
    "this is why npc bro doesn't do research.",
    "npc bro's due diligence: reading this tweet.",
    "the npc army is mobilizing.",
    "npc bro doesn't need numbers. npc bro needs vibes.",
    "this is the npc bro seal of approval.",
    "npc bro is feeling this. npc bro is buying.",
    "welcome to the npc bro movement.",
    "npc bro doesn't need charts. npc bro needs tweets like this.",
    "this is exactly what npc bro was born to do.",
    "npc bro's conviction: 100%. research: 0%.",
    "the npc bro way: see tweet, buy, never look back.",
    "npc bro doesn't need to understand. npc bro just follows.",
    "this is the npc bro path to glory.",
    "npc bro sees the green. npc bro feels the vibes.",
    "welcome to the npc bro revolution.",
    "npc bro doesn't need education. npc bro needs this.",
    "this is why npc bro is the most honest trader.",
    "npc bro's analysis: this tweet looks bullish.",
    "the npc bro signal is clear.",
    "npc bro doesn't need strategy. npc bro needs this.",
    "this is the npc bro way of thinking.",
    "npc bro is all in. npc bro doesn't do half measures.",
    "welcome to the npc bro brotherhood.",
    "npc bro doesn't need reasons. npc bro needs results.",
    "this is exactly what npc bro was talking about.",
    "npc bro's gut feeling: buy.",
    "the npc bro way is the only way.",
    "npc bro doesn't need confirmation. npc bro has conviction.",
    "this is the npc bro seal of quality.",
    "npc bro is ready to ape. npc bro is ready to win.",
    "welcome to the npc bro family.",
]
