"""
content_pool.py

Definitieve content pool: 95 foto-scenes + 468 tekst-only posts.
Bestandsnamen in PHOTO_SCENES matchen exact met de bestanden in images/.
"""

# 95 foto-scenes: (bestandsnaam in images/, caption)
PHOTO_SCENES = [
    ("01_headphones_phone.png", "npc bro, unbothered, checking the only thing that matters"),
    ("02_desk_trading.png", "npc bro's trading setup. no chair, no plan, all conviction"),
    ("03_green_arrow_rocket.png", "npc bro found the trajectory. npc bro is not moving."),
    ("04_crash_dive.png", "npc bro on the way down, still holding the phone"),
    ("05_coffee.png", "npc bro doesn't need coffee, npc bro needs liquidity"),
    ("06_sad_hodl.png", "npc bro closed his eyes. the chart did not close with him."),
    ("07_meme_green_candle_run.jpeg", "npc bro doesn't need a reason"),
    ("08_multi_monitor_wall.png", "npc bro's setup has more screens than friends"),
    ("09_running_phone.png", "npc bro heard about it 4 seconds ago and is already in"),
    ("10_standing_green_chart.png", "npc bro's face when it's up only. same face either way."),
    ("11_arms_crossed.png", "npc bro has made a decision. npc bro will not explain it."),
    ("12_meditation.png", "npc bro found inner peace. it's just the phone glowing."),
    ("13_confused_question.png", "npc bro doesn't know why he bought it either"),
    ("14_trophy.png", "npc bro won. npc bro is not sure at what."),
    ("15_broken_umbrella_rain.png", "npc bro's risk management, visualized"),
    # 21 nieuwe foto-scenes
    ("16_phone_chart.jpg", "npc bro found the chart. npc bro is not moving until it moves."),
    ("17_trading_screen.jpg", "npc bro's trading setup. more screens than brain cells."),
    ("18_desk_setup.jpg", "npc bro doesn't need a proper desk. npc bro needs liquidity."),
    ("19_phone_focus.jpg", "npc bro is locked in. the chart is the only thing that matters."),
    ("20_chart_stare.jpg", "npc bro has been staring at this chart for 4 hours. it hasn't moved. neither has npc bro."),
    ("21_gaming_setup.jpg", "npc bro's gaming setup. also his trading setup. also his life."),
    ("22_phone_bed.jpg", "npc bro doesn't sleep. npc bro just refreshes dexscreener horizontally."),
    ("23_desk_chair.jpg", "npc bro's ergonomic setup: whatever was on sale at ikea."),
    ("24_multiple_screens.jpg", "npc bro needs 6 screens to make decisions he doesn't understand."),
    ("25_trading_pose.jpg", "npc bro's trading posture. shoulders forward, eyes glazed, phone in hand."),
    ("26_phone_casual.jpg", "npc bro acting casual. npc bro is down 40% today."),
    ("27_desk_work.jpg", "npc bro working hard. by watching other people make money."),
    ("28_monitor_focus.jpg", "npc bro's monitor. npc bro's entire personality."),
    ("29_phone_check.jpg", "npc bro checking the chart. again. for the 47th time today."),
    ("30_trading_desk.jpg", "npc bro's command center. where dreams go to die."),
    ("31_phone_relaxed.jpg", "npc bro relaxed. npc bro just bought the top. it's fine."),
    ("32_desk_computer.jpg", "npc bro's computer. mostly used for refreshing twitter."),
    ("33_monitor_setup.jpg", "npc bro's monitor setup. designed for maximum fomo induction."),
    ("34_phone_stand.jpg", "npc bro standing. npc bro doesn't sit. npc bro doesn't think. npc bro just buys."),
    ("35_trading_focus.jpg", "npc bro in the zone. the zone where he loses money."),
    # 60 nieuwe scene scenes
    ("scene_01.png", "Opened the fridge for the fifth time. Still nothing new in there."),
    ("scene_02.png", "Walked into the room. The reason stayed outside."),
    ("scene_03.png", "Watched the microwave count down like it owed him an explanation."),
    ("scene_04.png", "Looked everywhere for his phone. It was in his hand the whole time."),
    ("scene_05.png", "Pressed the elevator button four more times. It did not arrive faster."),
    ("scene_06.png", "Walked into the glass door. Kept walking like it was part of the plan."),
    ("scene_07.png", "Stood in the aisle. Forgot the one thing he came for."),
    ("scene_08.png", "Put his car keys in the fridge. Found them next to the milk."),
    ("scene_09.png", "Sat on the bed. The reason for sitting never showed up."),
    ("scene_10.png", "Waited at a red light with no cars in sight. Waited anyway."),
    ("scene_11.png", "Plugged in the USB the wrong way three times. Fourth time, still wrong."),
    ("scene_12.png", "Scrolling on the couch with no destination in mind."),
    ("scene_13.png", "Set five alarms. Trusted none of them."),
    ("scene_14.png", "Sat on the gym bench and did reps on his phone instead."),
    ("scene_15.png", "Ordered the same meal again. Called it a routine."),
    ("scene_16.png", "Scrolled the streaming menu for twenty minutes. Watched nothing."),
    ("scene_17.png", "Stood in the shower. Water running. Brain not included."),
    ("scene_18.png", "Watched the toast burn. Didn't intervene."),
    ("scene_19.png", "Tried writing with a dead pen. Pressed harder. Still dead."),
    ("scene_20.png", "Walked back into the room. Forgot what for, again."),
    ("scene_21.png", "Pulled the door marked push. Pulled harder."),
    ("scene_22.png", "Pushed the door marked pull. Blamed the door."),
    ("scene_23.png", "Stared out the window at nothing in particular."),
    ("scene_24.png", "Wide awake at night. Eyes open. Nobody home."),
    ("scene_25.png", "One earbud in, looking productive, doing nothing."),
    ("scene_26.png", "Stared at the login screen. The password left without saying goodbye."),
    ("scene_27.png", "Made coffee. Never drank it. It's cold now. It's fine."),
    ("scene_28.png", "Held an empty cart in the aisle like it was a plan."),
    ("scene_29.png", "Checked the banking app after shopping. Regret loading."),
    ("scene_30.png", "Folded the laundry. Left the pile on the chair permanently."),
    ("scene_31.png", "Sat in the meeting. Nodded. Heard none of it."),
    ("scene_32.png", "3am. Ceiling. No conclusions reached."),
    ("scene_33.png", "Found one sock. The other one is a myth now."),
    ("scene_34.png", "Checked the clock every minute. Time moved slower for it."),
    ("scene_35.png", "Fought a shopping cart stuck to the others. Cart won."),
    ("scene_36.png", "Walked the wrong way down the street with full confidence."),
    ("scene_37.png", "Opened the fridge again. Expected it to be different this time."),
    ("scene_38.png", "Stood in the middle of the aisle. Became the obstacle."),
    ("scene_39.png", "Stood in the rain with no umbrella. Called it fresh air."),
    ("scene_41.png", "Peeled the sticker. It tore. It always tears."),
    ("scene_42.png", "Sat on the wrong train. Realized two stops too late."),
    ("scene_43.png", "Walked home for the wallet he forgot the wallet at home for."),
    ("scene_44.png", "Bought right after the spike. Called it good timing."),
    ("scene_45.png", "Sold right before it went up. Called it instinct."),
    ("scene_46.png", "Checked the chart every few seconds. Nothing changed each time."),
    ("scene_47.png", "Small red dip. Full internal crisis."),
    ("scene_48.png", "Told himself this time is different. It was not."),
    ("scene_49.png", "Refreshed the chart on the couch. The chart refreshed him back."),
    ("scene_50.png", "Bought it because everyone else was talking about it."),
    ("scene_51.png", "Sold out of fear. The chart didn't care either way."),
    ("scene_52.png", "Stared at candlesticks all night. Learned nothing new."),
    ("scene_53.png", "One green number, small smile. One red number, gone."),
    ("scene_54.png", "Checked the portfolio mid-dinner. Appetite: gone."),
    ("scene_55.png", "Checked the portfolio on the gym bench. Skipped the workout."),
    ("scene_56.png", "Checked the portfolio before opening his eyes fully."),
    ("scene_57.png", "Stared at one green candle like it meant something."),
    ("scene_58.png", "One red candle. App closed. Feelings not processed."),
    ("scene_59.png", "Watched the chart on TV with popcorn. Popcorn: fine. Chart: not fine."),
    ("scene_60.png", "Opened the portfolio app dozens of times sitting completely still."),
]

# 468 tekst-only posts (definitieve pool)
TEXT_POSTS = [
    # Relatable degen-gedrag
    "npc bro doesn't have a thesis. npc bro has vibes and a phone.",
    "npc bro's portfolio strategy: whatever's trending at 2am",
    "npc bro doesn't sell high. npc bro sells whenever he gets nervous.",
    "npc bro's biggest indicator is how many people are talking about it. that's it. that's the whole strategy.",
    "npc bro read one tweet and changed his entire life plan",
    "npc bro doesn't have a stop loss. npc bro has regret.",
    "npc bro checks the chart 47 times a day and still doesn't know what he's looking at",
    "npc bro's risk management: hope",
    "npc bro bought high, sold low, and still calls himself a trader",
    "npc bro doesn't do technical analysis. npc bro does vibes analysis.",
    # GM/GN
    "gm to everyone. especially npc bro, who is already checking the chart before his eyes are fully open",
    "gn to everyone except npc bro, who is still refreshing dexscreener at 3am",
    "gm. npc bro slept 4 hours and dreamed about green candles",
    "gn. tomorrow npc bro wakes up and does the exact same thing again",
    # Zelfspot/community
    "be honest, how many of you are secretly npc bro",
    "npc bro isn't a person. npc bro is a mirror.",
    "we're all npc bro sometimes. some of us just admit it.",
    "there's an npc bro in every group chat. if you don't know who it is, it might be you",
    "npc bro doesn't judge. npc bro just follows. respect the process.",
    "the npc army doesn't sleep, doesn't think, and definitely doesn't dyor",
    # Hype/community-opbouw
    "npc bro is coming. no research needed to understand why.",
    "$NPCBRO isn't the smartest coin on solana. it's the most honest one.",
    "if you've ever bought something because a stranger on CT told you to, welcome home",
    "npc bro doesn't need utility. npc bro needs vibes.",
    "the most relatable character in crypto is about to get a coin",
    # Losse observaties/humor
    "npc bro's wallet has 40 different tokens and he can't explain why he bought any of them",
    "npc bro doesn't read whitepapers. npc bro reads vibes.",
    "npc bro's favorite indicator is 'this guy seems confident'",
    "npc bro has never once said 'let me do some research first'",
    "somewhere right now, npc bro is buying something because of a reply guy with a rocket emoji in his bio",
    # Hype voor pump.fun launch
    "npc bro doesn't know what pump.fun is yet. but npc bro will be there when it matters.",
    "the npc lobby is loading... prepare for entry.",
    "npc bro has been preparing for this moment his whole life. by doing absolutely nothing.",
    "when $NPCBRO launches, npc bro will be first in line. because npc bro is always first in line.",
    "npc bro doesn't need a whitepaper. npc bro needs a green button.",
    "the npc army is gathering. no coordination needed. we just follow.",
    "pump.fun? npc bro thought that was the sound his portfolio makes.",
    "npc bro's launch strategy: wait for someone else to say it's good, then ape in.",
    "the npc lobby doesn't do research. the npc lobby does vibes.",
    "npc bro is coming to solana. bring your tendies.",
    "when $NPCBRO launches, npc bro won't read the tokenomics. npc bro will just buy.",
    "the npc lobby is open. no entry requirements. just lack of critical thinking.",
    "npc bro has been training for this launch. by scrolling CT for 12 hours a day.",
    "pump.fun is just npc bro's natural habitat.",
    "npc bro doesn't know when the launch is. npc bro will find out when everyone else does.",
    "the npc army doesn't need a signal. the npc army is the signal.",
    "npc bro's due diligence: checking if the emoji looks bullish.",
    "when $NPCBRO hits pump.fun, npc bro will be there. npc bro is always there.",
    "the npc lobby doesn't sleep. the npc lobby waits for the green candle.",
    "npc bro doesn't need a roadmap. npc bro needs a chart that goes up.",
    "pump.fun + npc bro = the most honest launch in solana history.",
    "npc bro's investment thesis: if it's trending, it's good.",
    "the npc lobby is where degens become legends. or lose everything. probably both.",
    "npc bro doesn't know what solana is. npc bro just knows it goes up sometimes.",
    "when $NPCBRO launches, npc bro will buy the top. because that's what npc bro does.",
    "the npc army doesn't need instructions. the npc army needs a green candle.",
    "npc bro's pre-launch strategy: refresh CT until something looks promising.",
    "pump.fun is where npc bro belongs. it's where vibes matter more than utility.",
    "npc bro doesn't need a marketing budget. npc bro needs other npc bros.",
    "the npc lobby is growing. one degen at a time.",
    "npc bro's favorite word: 'moon'. npc bro's second favorite: 'safu'.",
    "when $NPCBRO launches, npc bro won't ask questions. npc bro will just ape.",
    # 438 nieuwe tekst posts uit npcbro posts.txt
    "Opened the fridge. Closed the fridge. Opened it again.",
    "Walked into the kitchen. Forgot why. Walked out.",
    "Said \"you too\" when the waiter said enjoy your meal.",
    "Typed my password wrong three times then remembered it perfectly.",
    "Waved back at someone who wasn't waving at me.",
    "Refreshed the app I just closed.",
    "Set an alarm for 6am. Turned it off at 6:01am. No memory of it.",
    "Reheated the same coffee four times today.",
    "Walked past my exit. Kept walking. Didn't notice for ten minutes.",
    "Said \"good morning\" at 4pm.",
    "Checked the mailbox. Nothing there. Checked again an hour later.",
    "Laughed at a joke I didn't fully hear.",
    "Nodded along to a conversation I stopped listening to.",
    "Put my keys somewhere \"safe.\"",
    "Still looking for my keys.",
    "Replied \"lol\" to something that wasn't funny.",
    "Opened three tabs to look up the same thing.",
    "Forgot what I walked into the room for. Twice.",
    "Brushed my teeth. Can't remember doing it. Did it anyway.",
    "Said \"I'll remember this time.\" Did not remember.",
    "Autopilot got me home. I don't remember the drive.",
    "Stared at the fridge like it would say something back.",
    "Reorganized my desk instead of doing the actual task.",
    "Read the same sentence five times. Still don't know what it said.",
    "Clicked \"remind me later\" on everything.",
    "Told myself I'd sleep early. It's 2am.",
    "Ate breakfast. Immediately forgot what I ate.",
    "Said \"you're welcome\" before anyone said thank you.",
    "Walked into a room, turned around, walked out.",
    "Put my phone down for two seconds. Lost it for twenty minutes.",
    "Answered a question with a question I don't remember asking.",
    "Tried to open the door with my car key.",
    "Waited at a red light that was already green.",
    "Microwaved my food. Forgot to press start.",
    "Said \"same\" to something I don't relate to at all.",
    "Rewatched the same show because I forgot the ending.",
    "Made a to-do list. Lost the list.",
    "Texted \"on my way\" while still getting ready.",
    "Clapped along to a song with the wrong beat.",
    "Said \"no worries\" when there clearly were worries.",
    "Held the door for someone twenty feet away.",
    "Walked in circles looking for something in my hand.",
    "Repeated a story to the same person twice.",
    "Set three alarms. Slept through all of them.",
    "Nodded \"yes\" without hearing the question.",
    "Bought the same snack I already had at home.",
    "Said \"brb\" and never came back.",
    "Left the water running while thinking about something else.",
    "Tried to unlock my phone with someone else's fingerprint.",
    "Sat down to relax. Immediately got back up for no reason.",
    "Forgot the name of someone I just met.",
    "Introduced myself to someone I already know.",
    "Checked my phone. Locked it. Checked it again.",
    "Started a sentence with no idea how to end it.",
    "Laughed at my own joke before saying it out loud.",
    "Walked to the store. Forgot what I needed.",
    "Put the milk in the cupboard.",
    "Said \"see you tomorrow\" to someone I won't see tomorrow.",
    "Answered the door before it rang.",
    "Tried to swipe a paper page like a screen.",
    "Sent a text to the wrong person. Sent it anyway.",
    "Said \"one sec\" and disappeared for an hour.",
    "Turned off the tv, sat in silence, turned it back on.",
    "Googled something I already knew.",
    "Forgot I was holding my drink and set it down mid-air.",
    "Replied to an email three days late like it was on time.",
    "Said \"let's circle back\" and never circled back.",
    "Put my shoes on the wrong feet. Didn't notice for a while.",
    "Stared at the ceiling instead of sleeping.",
    "Said \"I'm listening\" while not listening.",
    "Woke up more tired than when I fell asleep.",
    "Repeated \"wait what\" four times in one conversation.",
    "Forgot to mute myself. Everyone heard it.",
    "Sent \"lol\" instead of \"lmk.\"",
    "Closed the laptop mid-task. Opened it again confused.",
    "Tried to pay with the wrong card. Twice.",
    "Said \"I'll be quick\" then wasn't.",
    "Left the charger at home again.",
    "Checked the time. Forgot the time immediately.",
    "Walked past the mirror. Did a double take at myself.",
    "Put my headphones on backwards.",
    "Started typing in the wrong chat.",
    "Said \"same time tomorrow\" with no plan of what time.",
    "Bought more snacks than actual groceries.",
    "Said \"hang on\" and forgot what I was doing.",
    "Reached for my phone before my eyes were even open.",
    "Said \"yeah for sure\" to something I didn't agree with.",
    "Sat in the parked car for ten extra minutes for no reason.",
    "Told the same joke to the same person again.",
    "Forgot to eat until 3pm.",
    "Said \"brb 5 min\" three hours ago.",
    "Walked into the glass door. Acted like it didn't happen.",
    "Left the tab open for a week. Never read it.",
    "Said \"I got this\" then clearly didn't.",
    "Set the table wrong, corrected it, still wrong.",
    "Put my drink down and immediately lost it.",
    "Said \"quick question\" then asked five.",
    "Nodded off mid-sentence in a meeting.",
    "Answered a text a day late with \"sorry just saw this.\"",
    "Forgot my own phone number when asked.",
    "Said \"trust the process\" with no process.",
    "Reset my password to the exact same password.",
    "Left the fan on all night for no reason.",
    "Said \"almost there\" while not moving at all.",
    "Bought a plant. Forgot it existed by day three.",
    "Told myself \"just five more minutes\" for two hours.",
    "Said \"no rush\" then immediately got impatient.",
    "Forgot which day it is. Guessed wrong.",
    "Put decaf in the machine. Wondered why nothing changed.",
    "Said \"brb charging my phone\" then fell asleep.",
    "Walked the long way home out of habit.",
    "Said \"wait I have a good one\" then blanked.",
    "Left one sock on all day.",
    "Said \"just checking in\" with nothing to check.",
    "Forgot to send the message I typed out.",
    "Restarted my phone for no functional reason.",
    "Said \"let me think about it\" then never thought about it.",
    "Reheated leftovers. Forgot them in the microwave.",
    "Said \"almost done\" at the very beginning.",
    "Told the barista my old order out of habit.",
    "Said \"not gonna lie\" before lying slightly.",
    "Forgot the plot of the movie I watched last night.",
    "Walked into the kitchen for water. Left with a snack instead.",
    "Said \"one more episode\" nine episodes ago.",
    "Left my umbrella at home on the one rainy day.",
    "Said \"I'll do it tomorrow\" for the fifth day straight.",
    "Set a reminder for the reminder I forgot to check.",
    "Told the same story with a different ending by accident.",
    "Said \"wait for real?\" to something I already knew.",
    "Forgot to lock the door. Went back to check. It was locked.",
    "Said \"you didn't have to\" while clearly wanting it.",
    "Put my card in backwards at the machine.",
    "Said \"almost forgot\" about something I definitely forgot.",
    "Left a notification unread for weeks out of principle.",
    "Told myself I'd stop scrolling. Kept scrolling.",
    "Said \"quick nap\" for three hours.",
    "Forgot the reason I opened my laptop.",
    "Said \"no comment\" then commented anyway.",
    "Left the light on in a room I wasn't in.",
    "Said \"let's not overthink this\" while overthinking it.",
    "Answered \"good, you?\" before hearing \"how are you.\"",
    "Forgot to save the file. Lost the file.",
    "Said \"next time for sure\" for the third time in a row.",
    "Bought the wrong size again.",
    "Said \"brand new day\" then repeated yesterday exactly.",
    "Walked in, sat down, immediately forgot the plan.",
    "Said \"we'll see\" knowing full well we wouldn't.",
    "Left the oven light on for hours by accident.",
    "Said \"10/10 would recommend\" without trying it.",
    "Forgot the joke halfway through telling it.",
    "Said \"small edit\" then rewrote the whole thing.",
    "Left three browser windows open doing nothing.",
    "Said \"quick call\" that lasted 45 minutes.",
    "Forgot to turn off airplane mode. Wondered why no signal.",
    "Said \"I've got a system\" with no system.",
    "Bought a book. Never opened it.",
    "Said \"let's not make this a thing\" made it a thing.",
    "Forgot the password. The hint made no sense either.",
    "Said \"wait I just said that\" mid-repeat.",
    "Left my sunglasses on my head the whole time looking for them.",
    "Said \"I'm not stressed\" while visibly stressed.",
    "Reused yesterday's plan for today accidentally.",
    "Said \"future me can deal with it.\"",
    "Bought coin at the top. Called it \"a dip.\"",
    "Sold coin at the bottom. Called it \"risk management.\"",
    "Bought back higher than I sold. Called it \"reentry.\"",
    "FOMO'd into a chart shaped like a mountain.",
    "Panic sold right before it went up.",
    "Said \"this time it's different\" for the tenth time.",
    "Bought the top. Again.",
    "Held through a 90% drop calling it \"conviction.\"",
    "Sold the bottom calling it \"cutting losses.\"",
    "Bought high, sold low, called it \"strategy.\"",
    "Said \"just one more trade\" for the hundredth trade.",
    "Refreshed the chart every four seconds. Nothing changed.",
    "Bought because of a chart pattern I made up in my head.",
    "Said \"I have a good feeling about this one.\"",
    "Bought the coin because the mascot looked funny.",
    "Ignored every red flag because the name was catchy.",
    "Said \"diamond hands\" while checking the price every minute.",
    "Bought high on hope. Sold low on fear.",
    "Called a 2% move \"the start of something huge.\"",
    "Said \"I'm early\" three months after everyone else.",
    "Bought the news. Sold the rumor. Backwards, somehow.",
    "Watched it 10x after selling. Said \"at least I learned something.\"",
    "Didn't learn anything.",
    "Bought based on a tweet with zero context.",
    "Said \"trust me bro\" to myself while trading.",
    "Panic bought the same coin I panic sold last week.",
    "Called every dip a \"generational buying opportunity.\"",
    "Averaged down into the floor.",
    "Said \"it can't go lower.\" It went lower.",
    "Set a stop loss. Moved it. Moved it again. Removed it.",
    "Bought high because \"everyone's talking about it.\"",
    "Sold low because \"everyone's scared.\"",
    "Missed the pump. Bought the dump.",
    "Said \"I'm playing with house money\" with real money.",
    "Called a rugpull \"a learning experience.\"",
    "Bought the exact top of a chart shaped like a rocket, briefly.",
    "Said \"next 100x is coming\" every single week.",
    "Told myself I wouldn't check the price. Checked the price.",
    "Bought a coin because the logo looked cool.",
    "Said \"fundamentals don't matter\" and meant it unironically.",
    "Held a bag so heavy it needed its own chair.",
    "Said \"I'll sell at break even\" three months ago.",
    "Still holding. Still saying it.",
    "Bought high. Watched it drop. Bought more. Watched it drop more.",
    "Called it \"dollar cost averaging\" out of denial.",
    "Said \"the chart looks bullish\" about a straight line down.",
    "Sold everything the day before it pumped.",
    "Bought everything the day before it dumped.",
    "Timing so bad it feels intentional.",
    "Said \"I'm not addicted, I just check often.\"",
    "Checked the price during a meeting.",
    "Checked the price at a red light.",
    "Checked the price while checking the price.",
    "Said \"this is my last trade\" starting a new trading career every week.",
    "Bought a coin purely because of the ticker symbol.",
    "Ignored the whitepaper. Read the memes instead.",
    "Said \"up only\" right before it wasn't.",
    "Bought the hype. Sold the silence.",
    "Called every green candle \"the beginning of the bull run.\"",
    "Called every red candle \"healthy correction.\"",
    "There is no correction. Just red.",
    "Said \"smart money is buying\" with zero evidence.",
    "Bought because a stranger online said \"trust me.\"",
    "Sold because a different stranger said \"get out now.\"",
    "Followed both. Lost both ways.",
    "Said \"I have an exit strategy.\" Never used it.",
    "Bought high, held through zero, sold at zero, bought again.",
    "Called it \"full circle.\"",
    "Said \"not financial advice\" then took financial advice from a meme.",
    "Bought a coin with a dog on it. Then a cat. Then both combined.",
    "Called the combination \"the next big thing.\"",
    "It was not the next big thing.",
    "Said \"I'm in it for the tech\" about a coin with no tech.",
    "Bought high on a Friday. Regretted it by Monday.",
    "Said \"weekends don't count\" about market losses.",
    "They counted.",
    "Refreshed the wallet balance hoping it changed by staring at it.",
    "It did not change by staring at it.",
    "Said \"I'm built different\" while making the same mistake as everyone.",
    "Bought the dip. It dipped again. Bought that dip too.",
    "Ran out of dips to buy.",
    "Said \"up big trust\" then it went to zero.",
    "Called losing money \"tuition.\"",
    "Never graduated.",
    "What's your biggest NPC moment?",
    "Be honest, how many times do you check your phone an hour?",
    "What's a habit you hate but still do every day?",
    "Have you ever bought the top and sold the bottom in the same week?",
    "What's the most \"autopilot\" thing you've ever done?",
    "Be honest, do you actually read the terms and conditions?",
    "What's a small lie you tell yourself every morning?",
    "How many unread notifications do you have right now?",
    "What's the dumbest reason you've ever bought a coin?",
    "Have you ever forgotten why you walked into a room? How often?",
    "What's your go-to excuse for procrastinating?",
    "Be honest, are you reading this instead of doing something else?",
    "What's the longest you've held a losing trade out of pure denial?",
    "What's a routine you do without even thinking about it?",
    "Have you ever panicked over nothing and pretended you were fine?",
    "What's the most \"NPC\" thing your brain has told you today?",
    "Be honest, how many tabs do you have open right now?",
    "What's something you say a lot but don't actually mean?",
    "Have you ever said \"last time\" and it wasn't the last time?",
    "What's the weirdest thing you've done on autopilot?",
    "Be honest, do you actually finish the shows you start?",
    "What's your worst crypto decision you're still not over?",
    "How many times have you set an alarm and ignored it?",
    "What's a small thing that ruins your whole day?",
    "Have you ever forgotten someone's name right after they said it?",
    "What's the most predictable mistake you keep making?",
    "Be honest, are you addicted to checking charts?",
    "What's something you do just because everyone else does it?",
    "Have you ever bought something impulsively and regretted it in five minutes?",
    "What's your default response when you're not actually paying attention?",
    "Be honest, how many times have you refreshed this app today?",
    "What's a decision you made purely out of boredom?",
    "Have you ever said \"I'm fine\" while clearly not fine?",
    "What's the most NPC thing about your morning routine?",
    "Be honest, do you actually stick to your to-do list?",
    "What's a trade you still think about at 3am?",
    "Have you ever repeated a mistake knowing it was a mistake?",
    "What's something you do on repeat without realizing it?",
    "Be honest, how many times have you said \"one more scroll\"?",
    "What's the most obvious red flag you've ever ignored?",
    "Have you ever bought a coin just because of the name?",
    "What's a habit loop you can't seem to break?",
    "Be honest, do you overthink small decisions constantly?",
    "What's your most \"same energy every day\" moment?",
    "Have you ever set a goal and forgotten it by lunch?",
    "What's something you do just to feel productive but isn't?",
    "Be honest, how often do you say \"brb\" and disappear for hours?",
    "What's the most robotic thing about your daily routine?",
    "Have you ever confidently done the wrong thing?",
    "What's a thought you have every single day without fail?",
    "Be honest, do you check the price more than you check the time?",
    "What's your most repeated financial mistake?",
    "Have you ever said \"trust the process\" with zero process?",
    "What's the laziest excuse you've used this week?",
    "Be honest, how many things are you procrastinating right now?",
    "What's a small win that felt bigger than it should have?",
    "Have you ever done something just because it was \"the vibe\"?",
    "What's your go-to move when you't know what to do?",
    "Be honest, do you actually plan your trades or just react?",
    "What's the most \"default setting\" thing about you?",
    "Have you ever said \"no more snacks\" while eating a snack?",
    "What's a pattern in your life you've noticed but not changed?",
    "Be honest, how many alarms does it take to wake you up?",
    "What's your most repeated regret this month?",
    "Have you ever confused being busy with being productive?",
    "What's something small that instantly resets your mood?",
    "Be honest, do you scroll before or after getting out of bed?",
    "What's your most \"on autopilot\" habit at work?",
    "Have you ever said \"this is fine\" while it clearly wasn't?",
    "What's the most NPC thing you've said this week?",
    "Loading...",
    "Brain.exe stopped working.",
    "Same bug, different day.",
    "System running on autopilot.",
    "Error 404: motivation not found.",
    "Buffering...",
    "Still loading.",
    "Task failed successfully.",
    "No updates available.",
    "Running on low battery.",
    "Signal lost.",
    "Processing... please wait.",
    "Restart didn't fix it.",
    "Cache cleared. Brain still slow.",
    "Default settings restored.",
    "Connection unstable.",
    "Background process: overthinking.",
    "Update postponed indefinitely.",
    "Memory full.",
    "Idle animation activated.",
    "System overload.",
    "Rebooting for no reason.",
    "Auto-save failed.",
    "Sync incomplete.",
    "Standby mode engaged.",
    "Battery at 1%. Still scrolling.",
    "Glitch in the routine.",
    "Frozen screen, unfrozen mind.",
    "Waiting for input.",
    "Ping timeout.",
    "Same loop, no exit.",
    "Took a shower. Forgot if I used shampoo. Used it again just in case.",
    "Said \"quick question\" and then never asked it.",
    "Left the grocery list at home. Bought everything except what I needed.",
    "Told myself I'd stretch this morning. Stretched for the phone instead.",
    "Said \"I'll text back in a sec\" four days ago.",
    "Walked outside. Forgot my jacket. Walked back in. Forgot it again.",
    "Said \"let me just finish this\" three episodes ago.",
    "Poured cereal before realizing there was no milk.",
    "Said \"I know exactly what I'm doing\" while completely lost.",
    "Locked myself out thinking about literally anything else.",
    "Said \"quick shower\" for forty-five minutes.",
    "Forgot to charge my phone. Remembered at 2% battery.",
    "Said \"I'll remember it this time\" and did not remember it.",
    "Put the remote in the fridge. Found it three days later.",
    "Said \"one more rep\" and did zero more reps.",
    "Set my alarm for pm instead of am.",
    "Said \"I'm on top of it\" while behind on everything.",
    "Reheated coffee that was already cold twice.",
    "Said \"I don't need notes, I'll remember\" forgot immediately.",
    "Walked to get something. Came back with something else entirely.",
    "Said \"quick nap, 10 minutes max\" woke up at midnight.",
    "Left my phone on silent. Missed everything important.",
    "Said \"I'll organize this weekend\" for the fortieth weekend.",
    "Watered a plant that was already dead.",
    "Said \"totally under control\" while nothing was under control.",
    "Forgot my own birthday plans until reminded.",
    "Said \"brb, five minutes\" and vanished for the rest of the day.",
    "Answered the phone with \"hello?\" to a text notification.",
    "Said \"I'll just skim it\" and read every single word twice.",
    "Put my seatbelt on after starting to drive.",
    "Said \"I've got a plan\" with absolutely no plan.",
    "Left the cart in the middle of the aisle without noticing.",
    "Said \"quick errand\" turned into the whole afternoon.",
    "Reread a message five times still didn't understand it.",
    "Said \"I'll wing it\" and it did not go well.",
    "Told the same \"quick story\" that took twenty minutes.",
    "Said \"I'm basically a morning person now\" then slept in.",
    "Forgot to hang up. Realized ten minutes later.",
    "Said \"small snack\" and finished the whole bag.",
    "Walked in the rain without an umbrella, again.",
    "Said \"this week I'm focused\" by Tuesday completely unfocused.",
    "Bought a coin because the countdown timer looked exciting.",
    "Sold because a red candle scared me for five seconds.",
    "Said \"I read the chart\" while just guessing.",
    "Bought high because \"it felt right.\"",
    "Panic sold into the exact bottom, on schedule.",
    "Said \"the dip is the buy,\" bought the top instead.",
    "Held a coin to zero out of pure stubbornness.",
    "Called stubbornness \"long term vision.\"",
    "Said \"I'm not emotional about this\" while clearly emotional.",
    "Bought based on a screenshot with no context.",
    "Sold based on a comment section, not the chart.",
    "Said \"smart money knows something.\" They did not.",
    "Bought high, waited, sold low, called it \"patience.\"",
    "Said \"I'm early\" while being extremely late.",
    "Rebought the same coin at a worse price, twice.",
    "Called it \"cost averaging.\" It was just bad timing.",
    "Said \"trust the chart.\" The chart said nothing useful.",
    "Bought a coin with a rocket emoji in the name. Obviously.",
    "Sold right before the rocket actually launched.",
    "Said \"I have diamond hands\" sold at the first red candle.",
    "Bought high on a Sunday. Regretted it by Sunday night.",
    "Said \"weekends are for gains\" they were not.",
    "Refreshed portfolio value hoping refreshing changed the outcome.",
    "Said \"up only\" during a straight downtrend.",
    "Bought a coin purely for the mascot's outfit.",
    "Called that \"due diligence.\"",
    "Said \"I have an edge.\" The edge was luck, and it ran out.",
    "Bought the top of a wick that lasted four seconds.",
    "Missed the real move entirely, again.",
    "Said \"next cycle for sure.\" Meant it every cycle.",
    "Have you ever bought something just to feel something?",
    "What's the most \"on autopilot\" purchase you've made?",
    "Be honest, how often do you say \"just five more minutes\"?",
    "What's a mistake you've made more than three times?",
    "Have you ever confidently given directions you weren't sure about?",
    "What's the last thing you did purely out of habit?",
    "Be honest, how many times have you restarted your phone today?",
    "What's a small task you've been avoiding for weeks?",
    "Have you ever forgotten your own plans the same day you made them?",
    "System error.",
    "Autopilot engaged.",
    "No signal detected.",
    "Refresh required.",
    "Still buffering.",
    "Task incomplete.",
    "Low memory warning.",
    "Reboot in progress.",
    "Ping failed.",
    "Default response loaded.",
]
